### ISSUE TITLE
WebRTC Radio

### ISSUE THREAD

**Issue by kmturley** [lminiero/jamrtc#1]
I was trying to achieve something similar. Wanted to show my project. Feel free to copy code if anything is helpful?
https://github.com/kmturley/webrtc-radio

**Comment by lminiero** [comment]
Thanks for the heads up! It looks like your project is P2P and web based, though?

I do know of people doing something similar using Janus as a server: using the Streaming plugin, you can provide the audio for the audio channel via plain RTP (e.g., using FFmpeg or GStreamer), and the Streaming plugin turns it into a WebRTC broadcast multiple people can subscribe to. A pseudo-live demo is available [here](https://janus.conf.meetecho.com/streamingtest), if you select the "War of the worlds" broadcast.

**Comment by kmturley** [comment]
Yes my project is web-based using p2p connections for streaming audio. There is a centralized web server which hosts the web app and keeps track of each connection using web sockets. But audio is streamed directly between the clients P2P, reducing the load on the server!

This means anyone can start a source stream and make it available on the local network, and anyone can then listen. Use case would be house parties, silent disco, university radio etc.

There is one hack needed, which is that Web Audio/Video by default can only access webcam and microphone. Users need to create a virtual microphone, which audio is mapped from their audio out of their instrument, so the high quality audio is shared.

Thanks for sharing the Janus example, will take a look. Native streaming apps can be more powerful e.g. with effects, lower latency and more advanced features. But a web stream democratizes access, most devices will be able to start/listen to streams without installing additional software. My example is trying to push the limits of web-based technologies
